apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-crud-k8s
  namespace: app1-staging
spec:
  selector:
    matchLabels:
      app: springboot-crud-k8s 
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-crud-k8s
    spec:
      containers:
      - name: springboot-crud-k8s
        image: dumln86/springboot-crud-k8s:__IMAGE_TAG__
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                  name: app-config
                  key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                  name: app-config
                  key: DB_NAME
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                  name: app-config
                  key: DB_HOST
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD