apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-k8s
  namespace: app1-staging
spec:
  selector:
    app: springboot-crud-k8s
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer