apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: app1-staging
spec:
  selector:
    matchLabels:
      app: hello 
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-world
        image: dumln86/e2e-pipeline:latest