apiVersion: v1
kind: Pod
spec:
  serviceAccount: jenkins-admin
  containers:
  - name: jnlp
    image: dumln86/jenkins-agent:1.0.5
    imagePullPolicy: Always
    command:
    - sleep
    args:
    - 99d
  volumes:
      - name: kaniko-secret
        secretVolume:
          secretName: dockercred
          mountPath: /kaniko/.docker
